version: "3.2"

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secret/password
    volumes:
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./mysql/password
        target: /secret/password
      #disabling the following mount points, in order to MariaDB container with non-persistent writes
      #- ./mysql/conf.d/my-noencrypt.cnf:/etc/mysql/conf.d/my.cnf
      #- ./mysql/data:/var/lib/mysql
      #- ./mysql/conf.d:/etc/mysql/conf.d
      #- ./mysql/key:/key

  api_sails:
    image: digiserve/ab-sails-api:test
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "1337:1337"
      - "9229:9229"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      - type: bind
        source: ./mysql/password
        target: /secret/password
      - type: bind
        source: ./data
        target: /app/data

  redis:
    image: docker.io/library/redis:6.2.1
    volumes:
      - type: bind
        source: ./redis/data
        target: /data
    command: redis-server --appendonly yes

  notification_email:
    image: docker.io/digiserve/ab-notification-email
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
    depends_on:
      - redis
      - api_sails

  process_manager:
    image: docker.io/digiserve/ab-process-manager:latest
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
    depends_on:
      - redis
      - api_sails
