name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: echu888
      DOCKERHUB_PW: 09235751-050f-4851-a295-803790e79652

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install npm packages
        run: npm install

      - name: Initialize docker swarm 
        run: docker swarm init
        
      - name: Login to docker hub 
        run: echo "$DOCKERHUB_PW" | docker login -u "$DOCKERHUB_USER" --password-stdin
        
      - name: Run installer script 
        run: npm run pull

      - name: Link in test configuration for docker swarm
        run: ln -s ../docker-compose.test.yml workdir/docker-compose.test.yml

      - name: Show GitHub commit information
        run: scripts/commit_info.sh

      - name:  Run tests
        run: npm run test
